---
sudo: required
language: python
services:
  - docker

before_install:
  - docker pull krig/crmsh:latest

script:
  - docker run -t -v "$(pwd):/app" krig/crmsh /bin/sh -c "systemctl start dbus; cd /app; ./test/run-in-container.sh"

after_failure:
  - sudo cat $TRAVIS_BUILD_DIR/crmtestout/regression.out $TRAVIS_BUILD_DIR/crmtestout/crm.*
